env:
  browser: true
  es2021: true
extends:
  - '@remix-run/eslint-config'
  - '@remix-run/eslint-config/node'
  - '@remix-run/eslint-config/jest-testing-library'
  - prettier
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - jest
  - jest-dom
  - testing-library
  - unused-imports
settings:
  jest:
    version: 27
  import/resolver:
    typescript: { }
rules:
  react/prop-types: off
  react/display-name: off
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - .tsx
        - .jsx
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.*'
  no-restricted-exports: off
  react/jsx-props-no-spreading: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  no-shadow: off
  '@typescript-eslint/no-shadow': off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  react/require-default-props: off
  unused-imports/no-unused-imports: error
