version: '3.6'
services:
  games:
    container_name: games
    image: games
    restart: unless-stopped
    ports:
      - 3018:2019
      - 3019:80
      - 3020:443
    volumes:
      - /home/x-wing/www/games/data:/data
      - /home/x-wing/www/games/config:/config
